### ISSUE TITLE
Element style attribute should not be obfuscated

### ISSUE THREAD

**Issue by aeadedoyin** [jd1378/nuxt-obfuscator#5] opened 2024-03-15 09:52 UTC
— Style attributes should be ignored.

![CleanShot X - 2024-03-15 at 10 50 41 AM@2x](https://github.com/jd1378/nuxt-obfuscator/assets/20503883/28d007dc-30de-462c-8778-917f7a086f62)

**Comment by jd1378** [comment] 2024-03-15 15:03
fixed in [v1.1.5](https://github.com/jd1378/nuxt-obfuscator/releases/tag/v1.1.5)

**Comment by aeadedoyin** [comment] 2024-03-15 16:10
Hi @jd1378, this update didn’t work.


After installing new version same thing
![CleanShot X - 2024-03-15 at 05 07 32 PM@2x](https://github.com/jd1378/nuxt-obfuscator/assets/20503883/dfa7303c-c1e5-433d-ade1-7b343acf983b)


Here is what it looks like originally
![CleanShot X - 2024-03-15 at 04 45 04 PM@2x](https://github.com/jd1378/nuxt-obfuscator/assets/20503883/9194c9f1-b14e-46f4-97bb-9aae7075a66e)

Reproduce this with 
```NuxtLoadingIndicator```

**Comment by jd1378** [comment] 2024-03-15 16:13
hmm
I'm pretty sure it should not happen, as I have written test for it
can you delete your node modules folder and try installing the newest version again ?  or simply go to your node_modules and see if you can see this regex inside the `nuxt-obfuscator`'s vite-plugin file:
```
/(?<!(?:style|v-[\w]+|:\w+)=)(["'])(.*?)(?=\1)/
```

**Comment by aeadedoyin** [comment] 2024-03-15 16:20
@jd1378 

I made sure everything was fresh.

```
rm -rf .nuxt node_modules
rm obfuscation.map.json
npx nuxi cleanup
pnpm add nuxt-obfuscator@1.1.5
```

Then I tested locally with. 
`pnpm build`

same thing.

Test with this Nuxt component
```
<NuxtLoadingIndicator>
```


I can see the regex:
![CleanShot X - 2024-03-15 at 05 19 41 PM@2x](https://github.com/jd1378/nuxt-obfuscator/assets/20503883/af384787-e64f-4266-8f19-c68e8f573ac1)

**Comment by jd1378** [comment] 2024-03-15 16:21
I ran the test again with NuxtLoadingIndicator and it still passes
there must be something I'm missing

what is the version of your node ?

**Comment by aeadedoyin** [comment] 2024-03-15 16:23
`v20.11.1`

![CleanShot X - 2024-03-15 at 05 22 36 PM@2x](https://github.com/jd1378/nuxt-obfuscator/assets/20503883/adcf7cf8-d889-402f-a002-47aded747f76)

**Comment by jd1378** [comment] 2024-03-15 16:27
can I see your obfuscator config ?

**Comment by jd1378** [comment] 2024-03-15 16:28
this is weird, I have added NuxtLoadingIndicator both in test and [in playground](https://github.com/jd1378/nuxt-obfuscator/blob/0bca931ac6e99c69931a7ac6791275c9fdb50bb5/playground/app.vue#L10)
I have built the playground and it seems to be obfuscated properly:
![image](https://github.com/jd1378/nuxt-obfuscator/assets/6196533/8fcc05ab-0d0f-4a62-9263-dd76e815bc05)

**Comment by aeadedoyin** [comment] 2024-03-15 16:34
@jd1378 

> can I see your obfuscator config ?


![CleanShot X - 2024-03-15 at 05 32 13 PM@2x](https://github.com/jd1378/nuxt-obfuscator/assets/20503883/04783d11-da6a-4256-9b25-9f4c6f177752)

Also:
Not sure if this helps at all: I use tailwind nuxt and as you know it has classes like `fixed`, `absolute` etc.

**Comment by jd1378** [comment] 2024-03-15 16:35
this project was built for another project with tailwind initially, so there shouldn't be a problem, and if there is I am willing to solve it

**Comment by jd1378** [comment] 2024-03-15 16:39
oh, hmm, my first guess is the jsx is causing the problem, if you are using jsx
that's the only difference I can spot so far

perhaps you can put a breakpoint or `console.log` on [here](https://github.com/jd1378/nuxt-obfuscator/blob/0bca931ac6e99c69931a7ac6791275c9fdb50bb5/src/build/vite-plugin.ts#L22)
to provide me with more info

I'd like to know how the `code` looks like in transform function in your codebase and the matched regex
so I can spot if there's any issue with the jsx stuff

**Comment by aeadedoyin** [comment] 2024-03-15 16:44
@jd1378 

|default.vue layout|app.vue|
|--|--|
|![CleanShot X - 2024-03-15 at 05 37 19 PM@2x](https://github.com/jd1378/nuxt-obfuscator/assets/20503883/b34d519e-aef4-47a7-90a5-1c647dce8ef4)|![CleanShot X - 2024-03-15 at 05 38 44 PM@2x](https://github.com/jd1378/nuxt-obfuscator/assets/20503883/78b5f16f-eac1-493c-8044-7b1520c0240c)|


For this:
> oh, hmm, my first guess is the jsx is causing the problem, if you are using JSX that's the only difference I can spot so far

No, I am not using JSX, strictly Vue files, I just grabbed the config from the readme and edited the `nameLength`

**Comment by jd1378** [comment] 2024-03-15 16:48
either way I think it's best to put a breakpoint and see if you can spot what's going wrong

the only way I can imagine it not working properly is that the lookbehind inside the regex is being ignored/not working somehow

**Comment by aeadedoyin** [comment] 2024-03-15 16:50
@jd1378 Can invite you privately to the repo?

**Comment by jd1378** [comment] 2024-03-15 16:52
sorry, but please try to make a minimal reproduction

**Comment by aeadedoyin** [comment] 2024-03-15 16:57
It's a project that can also being opened later, so I can sure invite you on it, but I completely understand.

**Comment by aeadedoyin** [comment] 2024-03-15 16:57
So I have tried to log m, p1 and p2, can I also log the file, how do I get the file name currently replaced.

**Comment by jd1378** [comment] 2024-03-15 16:58
`id` I guess?

**Comment by aeadedoyin** [comment] 2024-03-15 17:03
@jd1378 Curious why not target the `:class="..."` and `class="..."` instead of the regex that ignores.

**Comment by jd1378** [comment] 2024-03-15 17:05
because many times there are quotes that contain class names that are not inside a template but needs to be obfuscated

**Comment by aeadedoyin** [comment] 2024-03-15 17:09
> because many times there are quotes that contain class names that are not inside a template but needs to be obfuscated like inside a `.ts` file instead of `.vue`

Ahh gotcha.



So after console logging this, here this one that concerns the nuxt-loading-indicator
```
Filename:  /<project-path>/node_modules/.pnpm/nuxt@3.10.3_eslint-ts-patch@8.57.0-0_rollup@2.79.1_typescript@5.0.4_vite@5.1.6/node_modules/nuxt/dist/app/components/nuxt-loading-indicator.js
--- --- ---
m:  "#app/composables/loading-indicator
p1:  "
p2:  #app/composables/loading-indicator
Filename:  /<project-path>/node_modules/.pnpm/nuxt@3.10.3_eslint-ts-patch@8.57.0-0_rollup@2.79.1_typescript@5.0.4_vite@5.1.6/node_modules/nuxt/dist/app/components/nuxt-loading-indicator.js
--- --- ---
m:  "NuxtLoadingIndicator
p1:  "
p2:  NuxtLoadingIndicator
Filename:  /<project-path>/node_modules/.pnpm/nuxt@3.10.3_eslint-ts-patch@8.57.0-0_rollup@2.79.1_typescript@5.0.4_vite@5.1.6/node_modules/nuxt/dist/app/components/nuxt-loading-indicator.js
--- --- ---
m:  "repeating-linear-gradient(to right,#00dc82 0%,#34cdfe 50%,#0047e1 100%)
p1:  "
p2:  repeating-linear-gradient(to right,#00dc82 0%,#34cdfe 50%,#0047e1 100%)
Filename:  /<project-path>/node_modules/.pnpm/nuxt@3.10.3_eslint-ts-patch@8.57.0-0_rollup@2.79.1_typescript@5.0.4_vite@5.1.6/node_modules/nuxt/dist/app/components/nuxt-loading-indicator.js
--- --- ---
m:  "div
p1:  "
p2:  div
Filename:  /<project-path>/node_modules/.pnpm/nuxt@3.10.3_eslint-ts-patch@8.57.0-0_rollup@2.79.1_typescript@5.0.4_vite@5.1.6/node_modules/nuxt/dist/app/components/nuxt-loading-indicator.js
--- --- ---
m:  "nuxt-loading-indicator
p1:  "
p2:  nuxt-loading-indicator
Filename:  /<project-path>/node_modules/.pnpm/nuxt@3.10.3_eslint-ts-patch@8.57.0-0_rollup@2.79.1_typescript@5.0.4_vite@5.1.6/node_modules/nuxt/dist/app/components/nuxt-loading-indicator.js
--- --- ---
m:  "fixed
p1:  "
p2:  fixed
Filename:  /<project-path>/node_modules/.pnpm/nuxt@3.10.3_eslint-ts-patch@8.57.0-0_rollup@2.79.1_typescript@5.0.4_vite@5.1.6/node_modules/nuxt/dist/app/components/nuxt-loading-indicator.js
--- --- ---
m:  "none
p1:  "
p2:  none
Filename:  /<project-path>/node_modules/.pnpm/nuxt@3.10.3_eslint-ts-patch@8.57.0-0_rollup@2.79.1_typescript@5.0.4_vite@5.1.6/node_modules/nuxt/dist/app/components/nuxt-loading-indicator.js
--- --- ---
m:  "auto
p1:  "
p2:  auto
Filename:  /<project-path>/node_modules/.pnpm/nuxt@3.10.3_eslint-ts-patch@8.57.0-0_rollup@2.79.1_typescript@5.0.4_vite@5.1.6/node_modules/nuxt/dist/app/components/nuxt-loading-indicator.js
--- --- ---
m:  "left
p1:  "
p2:  left
Filename:  /<project-path>/node_modules/.pnpm/nuxt@3.10.3_eslint-ts-patch@8.57.0-0_rollup@2.79.1_typescript@5.0.4_vite@5.1.6/node_modules/nuxt/dist/app/components/nuxt-loading-indicator.js
--- --- ---
m:  "transform 0.1s, height 0.4s, opacity 0.4s
p1:  "
p2:  transform 0.1s, height 0.4s, opacity 0.4s
Filename:  /<project-path>/node_modules/.pnpm/nuxt@3.10.3_eslint-ts-patch@8.57.0-0_rollup@2.79.1_typescript@5.0.4_vite@5.1.6/node_modules/nuxt/dist/app/components/nuxt-loading-indicator.js
--- --- ---
m:  'vue
p1:  '
p2:  vue
```

**Comment by jd1378** [comment] 2024-03-15 17:11
could you also get the `code` ? it's important for understanding the reason for matching

**Comment by aeadedoyin** [comment] 2024-03-15 17:13
File Path
```
<project-path>/node_modules/.pnpm/nuxt@3.10.3_eslint-ts-patch@8.57.0-0_rollup@2.79.1_typescript@5.0.4_vite@5.1.6/node_modules/nuxt/dist/app/components/nuxt-loading-indicator.js
```

Code
```js
import { defineComponent, h } from "vue";
import { useLoadingIndicator } from "#app/composables/loading-indicator";
export default defineComponent({
  name: "NuxtLoadingIndicator",
  props: {
    throttle: {
      type: Number,
      default: 200
    },
    duration: {
      type: Number,
      default: 2e3
    },
    height: {
      type: Number,
      default: 3
    },
    color: {
      type: [String, Boolean],
      default: "repeating-linear-gradient(to right,#00dc82 0%,#34cdfe 50%,#0047e1 100%)"
    },
    estimatedProgress: {
      type: Function,
      required: false
    }
  },
  setup(props, { slots, expose }) {
    const { progress, isLoading, start, finish, clear } = useLoadingIndicator({
      duration: props.duration,
      throttle: props.throttle,
      estimatedProgress: props.estimatedProgress
    });
    expose({
      progress,
      isLoading,
      start,
      finish,
      clear
    });
    return () => h("div", {
      class: "nuxt-loading-indicator",
      style: {
        position: "fixed",
        top: 0,
        right: 0,
        left: 0,
        pointerEvents: "none",
        width: "auto",
        height: `${props.height}px`,
        opacity: isLoading.value ? 1 : 0,
        background: props.color || void 0,
        backgroundSize: `${100 / progress.value * 100}% auto`,
        transform: `scaleX(${progress.value}%)`,
        transformOrigin: "left",
        transition: "transform 0.1s, height 0.4s, opacity 0.4s",
        zIndex: 999999
      }
    }, slots);
  }
});

```

**Comment by jd1378** [comment] 2024-03-15 17:15
ahhhhh, it finally makes sense
hmmmm
I need to think about this

**Comment by jd1378** [comment] 2024-03-16 00:44
Hi @aeadedoyin 
can you try out v2 ? I'm hoping that this settles things.

**Comment by jd1378** [comment] 2024-03-16 04:05
hi again @aeadedoyin 
can you test v2.0.1 now ?

**Comment by jd1378** [comment] 2024-03-17 00:48
I assume this is working as expected now, feel free to reopen if there's any issues

**Closed by jd1378** 2024-03-17 00:48 UTC
